### ISSUE TITLE
Move percent encoding mechanism to Vapor

### ISSUE THREAD

**Issue by twof** [vapor/routing-kit#72]
Percent encoding is mostly HTTP specific and feels out out of place in this package. I suggest we move the mechanism to Vapor. There are a few other options.

- Make percent encoding an option just like case sensitivity
- See if we can create a more general mechanism so that users of the package can create and use their own encodings.

Along with providing more flexibility, making it so that we can, at the very least, opt out of percent encoding, will help with performance benchmarks.

**Comment by twof** [comment]
Thoughts @tanner0101 ?

**Comment by tanner0101** [comment]
I agree with the sentiment that this feels HTTP specific. Although I'm not sure the best way to do it since we don't want to percent-decode _everything_, just the parameter. And we only know that after everything has been parsed. 

Maybe if we made percent-decoding a configurable feature of the router, it would feel less like a baked-in HTTP-specific thing?
